1.	Write a Python Program to Add Two Matrices?
2.	Write a Python Program to Multiply Two Matrices?
3.	Write a Python Program to Transpose a Matrix?
4.	Write a Python Program to Sort Words in Alphabetic Order?
5.	Write a Python Program to Remove Punctuation From a String?

*A class to descibe all these methods*

In [1]:
import numpy as np

In [102]:
class assignment_8:
    def metrics_add(x,y):
        result = [[x[i][j]+y[i][j] for j in range(len(x[0]))]
                  for i in range(len(x))]
        return np.array(result)
    def metrics_multiply(x,y):
        result = [[0 for i in range(len(x))]for j in range(len(y[0]))]
        try:
            for i in range(len(x)):
                for j in range(len(y[0])):
                    for k in range(len(y)):
                        result[i][j] += x[i][k]*y[k][j]
        except:
            print("please enter matrix with shape mxn and nxq")
        return np.array(result)
    def metrics_transpose(x):
        result = [[x[i][j] for i in range(len(x[0]))]for j in range(len(x))]
        return np.array(result)
    def alpha_sorting(scentence):
        y = [alpha.lower() for alpha in scentence.split()]
        y.sort()
        return y
    def remove_punctuation(str_): 
        punc = '!@#$%^&*.,?;:'
        for x in str_:
            if x in punc:
                str_ =str_.replace(x,' ')
        print(str_)
        
        
        
            

In [103]:
mat_1 = [[1,2,3],
        [4,5,6],
        [7,8,9]]
mat_2 = [[9,8,7],
        [6,5,4],
        [3,2,1]]
obj = assignment_8
obj.metrics_add(mat_1,mat_2)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [104]:
obj.metrics_multiply(mat_1,mat_2)



array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [105]:
obj.metrics_transpose(mat_1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [106]:
obj.alpha_sorting('dfeacbh')

['dfeacbh']

In [107]:
x = 'Its my life its now or never'
obj.alpha_sorting(x)



['its', 'its', 'life', 'my', 'never', 'now', 'or']

In [108]:
y = "this.is my life, and its an awesome, life, for . me to leave"
obj.remove_punctuation(y)



this is my life  and its an awesome  life  for   me to leave
